---
- name: Run latest version
  hosts: _UI
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: run server
    shell:
      cmd: nohup bash -c "BACK_HOST='{{ lookup('env', 'BACK_HOST') }}' node /home/ubuntu/app/server.js &"